name: norminette
'on':
  - push
  - pull_request
jobs:
  src:
    runs-on: ubuntu-latest
    name: standard of src
    steps:
      - uses: actions/checkout@v2
      - uses: alexandregv/norminette-action@v3
        with:
          flags: src/
  includes:
    runs-on: ubuntu-latest
    name: standard of includes
    steps:
      - uses: actions/checkout@v2
      - uses: alexandregv/norminette-action@v3
        with:
          flags: includes/
  libft:
    runs-on: ubuntu-latest
    name: standard of libft
    steps:
      - uses: actions/checkout@v2
      - uses: alexandregv/norminette-action@v3
        with:
          flags: libft/